all: array_struct_person.o
	g++ -o array_struct_person array_struct_person.o

array_struct_person.o: array_struct_person.cc
	g++ -c -o array_struct_person.o array_struct_person.cc

clean:
	rm array_struct_person.o


